# Generated by Django 5.0.6 on 2024-05-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("shortdesc", models.TextField()),
                ("tech", models.CharField(max_length=30)),
                ("longdesc", models.TextField()),
            ],
        ),
    ]
