# Generated by Django 5.0.6 on 2024-05-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="demolink",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="gitlink",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
