# Generated by Django 5.0.6 on 2024-05-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exp", "0004_alter_experience_techused"),
        ("projects", "0002_project_demolink_project_gitlink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="tech",
        ),
        migrations.AddField(
            model_name="project",
            name="tech",
            field=models.ManyToManyField(blank=True, to="exp.tech"),
        ),
    ]
