# Generated by Django 5.0.6 on 2024-05-15 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exp", "0002_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experience",
            options={"ordering": ["start"]},
        ),
    ]
